logging:
  level:
    ROOT: ERROR
    io.zenwave360.example: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.modulith: DEBUG
    org.springframework.modulith.events.core.DefaultEventPublicationRegistry: off

MONGODB_URI: mongodb://localhost:27017/online-food-delivery?replicaSet=rs0
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
SCHEMA_REGISTRY_URL: http://localhost:8081
