logging:
  level:
    io.zenwave360.example: DEBUG

management.endpoints.web.exposure.include: "*"

springdoc.swagger-ui.urls:
  - name: Customer
    url: /apis/openapi-customers.yml
  - name: Orders
    url: /apis/openapi-orders.yml
  - name: Restaurants
    url: /apis/openapi-restaurants.yml
  - name: Delivery
    url: /apis/openapi-delivery.yml

spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  data:
    mongodb:
      uri: ${MONGODB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
    producer:
      auto.register.schemas: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    stream:
      kafka.binder.enable-observation: true
      bindings:
        ## Orders Module Bindings
        on-order-event-out-0:
          destination: orders.order_details
        on-order-status-updated-out-0:
          destination: orders.order_status_updates
