logging:
  level:
    ROOT: ERROR
    io.zenwave360.example: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

MONGODB_URI: mongodb://localhost:27017/online-food-delivery?replicaSet=rs0
