logging:
  level:
    io.zenwave360.example: DEBUG

management.endpoints.web.exposure.include: "*"

springdoc.swagger-ui.urls:
  - name: Customer
    url: /apis/openapi-customers.yml
  - name: Orders
    url: /apis/openapi-orders.yml
  - name: Restaurants
    url: /apis/openapi-restaurants.yml
  - name: Delivery
    url: /apis/openapi-delivery.yml

spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  data:
    mongodb:
      uri: ${MONGODB_URI}
#  modulith.events.externalization.enabled: true
#  kafka:
#    bootstrap-servers: localhost:9092
