logging:
  level:
    io.zenwave360.example: DEBUG

management.endpoints.web.exposure.include: "*"
management.tracing.sampling.probability: 1.0

spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  data:
    mongodb:
      uri: ${MONGODB_URI}
